### ISSUE TITLE
Написать Laouyt.exe

### ISSUE THREAD

**Issue by okulovsky** [air-labs/VideoLectures#18]
Прогрмма по параметрам [файл картинки] [строка 1] [строка 2] [выходной файл] [dimensions]

должна генерить в выходной файл изображение, соответствующее layout:

<table><tr><td><image src=image></td><td><h1>строка1</h1><h2>строка 2</h2></td></tr></table>

Winforms
var bmp=new Bitmap(dimensions);
var graphics=bmp.CreateGraphics() ? Graphics.FromBMP();

var secBmp=(Bitmap)Bitmap.FromFile();
graphics.DrawBitmap();

raphics.DrawString( StringAlignment, Rectangle)

**Comment by Rast1234** [comment]
done
