### ISSUE TITLE
Рефакторинг Montager

### ISSUE THREAD

**Issue by okulovsky** [air-labs/VideoLectures#24]
1. Впилить его рядом с Praat.
2. Перевести на model.Montage.Chunks, + модульные тесты (обновить имеющиеся)
3. Режимы работы:
   общий: генерация команд FFMPEG
   нормальный режим: выполнять! Как в Praat
   если есть аргумент командной строки bat (Newname montage 11 bat) - выводить в консоль, а переправление как-нибудь.

**Comment by Rast1234** [comment]
1. сделано, теперь это еще один сервис
2. перевел на новые чанки. старые тесты подтягивать не стал.
3. можно выполнить  команды или вывести в консоль
